### ISSUE TITLE
DPU for Zynq7000

### ISSUE THREAD

**Issue by luminita02** [dvdsosa/DPUCZDX8G-IP#1]
Is this IP suitable for Zedboard with Zynq7000?
Or can you provide the DPU IP suitable for zynq7000?
Thank you!

**Comment by dvdsosa** [comment]
> Is this IP suitable for Zedboard with Zynq7000? Or can you provide the DPU IP suitable for zynq7000? Thank you!

As far as I read on the AMD docs in [here](https://support.xilinx.com/s/article/76742?language=en_US), the last release compatible with 7000 devices is Vitis-AI 1.4, so you should look on there.
